apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: ballot
  name: {{ .Values.services.ballot.serviceName }}
  namespace: {{ .Values.namespace }}
spec: 
  selector: 
    app: ballot
  ports:
  - name: http
    port: {{ .Values.httpServicePort }}
    targetPort: 8080
  type: LoadBalancer
