steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'ballot'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/ballot-test', './ballot']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/ballot-test']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run','deploy','ballot','--image','gcr.io/${PROJECT_ID}/ballot-test','--region','asia-south1','--min-instances','1','--allow-unauthenticated']
  env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-south1'
      - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
      
# - name: 'gcr.io/cloud-builders/docker'
#   id: 'ecserver'
#   args: ['build', '-t', 'gcr.io/${PROJECT_ID}/ec-server-test', './ecserver']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/${PROJECT_ID}/ec-server-test']
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['run','deploy','ecserver','--image','gcr.io/${PROJECT_ID}/ec-server-test','--region','asia-south1','--min-instances','1','--allow-unauthenticated']


# - name: 'gcr.io/cloud-builders/docker'
#   id: 'election-commision'
#   args: ['build', '-t', 'gcr.io/${PROJECT_ID}/election-commission-test', './election-commission']
#   env: 
#    - EC_SERVER_ENDPOINT='ecserver'
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/${PROJECT_ID}/election-commission-test']
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['run','deploy','election-commission','--image','gcr.io/${PROJECT_ID}/election-commission-test','--region','asia-south1','--min-instances','1','--allow-unauthenticated']

# - name: 'gcr.io/cloud-builders/docker'
#   id: 'voter'
#   args: ['build', '-t', 'gcr.io/${PROJECT_ID}/voter-test', './voter']
#   env: 
#    - REACT_APP_EC_SERVER_ENDPOINT='ecserver'
#    - REACT_APP_BALLOT_ENDPOINT='ballot'
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/${PROJECT_ID}/voter-test']
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['run','deploy','voter','--image','gcr.io/${PROJECT_ID}/voter-test','--region','asia-south1','--min-instances','1','--allow-unauthenticated']