# Default values for vote.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


httpServicePort: &defaultServicePort 80
ingressHost: current-cluster-roost.io
tag: &defaultTag latest
namespace: default

services:
  voter: 
    imageName: local-registry:5002/voter
    imageTag: *defaultTag
    serviceName: "voter"
    servicePort: *defaultServicePort
    host: voter.10.10.0.10.nip.io # host would be prefixed with namespace. (e.g. default.voter.)
  ballot: 
    imageName: local-registry:5002/ballot 
    imageTag: *defaultTag
    serviceName: "ballot"
    servicePort: *defaultServicePort
    host: ballot.10.10.0.10.nip.io # host would be prefixed with namespace. (e.g. default.ballot.)
  electionCommission: 
    imageName: local-registry:5002/election-commission
    imageTag: *defaultTag
    serviceName: "election-commission"
    servicePort: *defaultServicePort
    host: ec.10.10.0.10.nip.io # host would be prefixed with namespace. (e.g. default.ec.)
  ecserver: 
    imageName: local-registry:5002/ecserver
    imageTag: *defaultTag
    serviceName: "ecserver"
    servicePort: *defaultServicePort
    host: ecserver.10.10.0.10.nip.io # host would be prefixed with namespace. (e.g. default.ecserver.)
