# Default values for vote.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


httpServicePort: &defaultServicePort 80

services:
  voter: 
    image: local-registry:5002/voter:latest
    ingressEndpoint: "/voter/"
    serviceName: "voter"
    servicePort: *defaultServicePort
  ballot: 
    image: local-registry:5002/ballot:latest
    ingressEndpoint: "/ballot/"
    serviceName: "ballot"
    servicePort: *defaultServicePort
  electionCommission: 
    image: local-registry:5002/election-commission:latest
    ingressEndpoint: "/ec/"
    serviceName: "election-commission"
    servicePort: *defaultServicePort
  ecserver: 
    image: local-registry:5002/ecserver:latest
    ingressEndpoint: "/ecserver/"
    serviceName: "ecserver"
    servicePort: *defaultServicePort
