apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/use-port-in-redirects: "true"
    # nginx.ingress.kubernetes.io/app-root : "/voter"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/port_in_redirect: "off"
    # nginx.ingress.kubernetes.io/use-regex: "true"
    # ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: ecingress
  namespace: default
spec:
  # defaultBackend:
  #   service:
  #     name: {{ .Values.services.ballot.serviceName }}
  #     port:
  #       number: {{ .Values.services.ballot.servicePort }}
  rules:
    - host: roost-controlplane
      http:
        paths:
        - path: {{ .Values.services.ballot.ingressEndpoint }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.services.ballot.serviceName}}
              port:
                number: {{ .Values.services.ballot.servicePort }}
        - path: {{ .Values.services.voter.ingressEndpoint }}
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.services.voter.serviceName}}
              port:
                number: {{ .Values.services.voter.servicePort }}
    - http:
        paths: 
        {{- with $.Values.services }}
        - path: {{ .electionCommission.ingressEndpoint }}
          pathType: Prefix
          backend:
            service:
              name: {{ .electionCommission.serviceName}}
              port:
                number: {{ .electionCommission.servicePort }}
        - path: {{ .ecserver.ingressEndpoint }}
          pathType: Prefix
          backend:
            service:
              name: {{ .ecserver.serviceName}}
              port:
                number: {{ .ecserver.servicePort }}
        {{- end }}